package domain

import (
	"gorm.io/gorm"
)

// Staff model - tenant isolation is handled at schema level
type Staff struct {
	gorm.Model
	Username    string `json:"username" gorm:"uniqueIndex;not null,min=5,max=100"`
	Password    string `json:"-" gorm:"not null"`
	StaffCode   string `json:"staff_code" gorm:"uniqueIndex;not null"`
	PhoneNumber string `json:"phone_number" gorm:"uniqueIndex;not null"`
	Email       string `json:"email" gorm:"uniqueIndex;not null,email"`
	FirstName   string `json:"first_name" gorm:"not null,max=255"`
	LastName    string `json:"last_name" gorm:"not null,max=255"`
	IsAdmin     bool   `json:"is_admin" gorm:"default:false"`
}

type StaffResponse struct {
	ID          uint   `json:"id"`
	Username    string `json:"username"`
	StaffCode   string `json:"staff_code"`
	PhoneNumber string `json:"phone_number"`
	Email       string `json:"email"`
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
	IsAdmin     bool   `json:"is_admin"`
}

// StaffCreateRequest represents the create request payload
type StaffCreateRequest struct {
	Username string `json:"username" binding:"required,min=5,max=100"`
	Password string `json:"password" binding:"required,min=6"`
	// staffCode is auto generated by the system, not required
	StaffCode   string `json:"staff_code" binding:"omitempty"`
	PhoneNumber string `json:"phone_number" binding:"required"`
	Email       string `json:"email" binding:"required,email"`
	FirstName   string `json:"first_name" binding:"required,max=255"`
	LastName    string `json:"last_name" binding:"required,max=255"`
	IsAdmin     bool   `json:"is_admin" default:"false"`
}

// StaffUpdateRequest represents the update request payload
type StaffUpdateRequest struct {
	StaffCode   string `json:"staff_code" binding:"max=10"`
	PhoneNumber string `json:"phone_number" binding:"required,max=10"`
	Email       string `json:"email" binding:"required,email"`
	FirstName   string `json:"first_name" binding:"max=255"`
	LastName    string `json:"last_name" binding:"max=255"`
	IsAdmin     bool   `json:"is_admin"`
}

// StaffLoginRequest represents the login request payload (no hospitalID needed - tenant provides isolation)
type StaffLoginRequest struct {
	Username string `json:"username" binding:"required,min=5,max=100"`
	Password string `json:"password" binding:"required,min=6"`
}

// StaffLoginResponse represents the login response payload
type StaffLoginResponse struct {
	Token string        `json:"token"`
	Staff StaffResponse `json:"staff"`
}

// StaffRepository interface - tenant schema provides isolation
type StaffRepository interface {
	GetAll(schemaName string) ([]Staff, error)
	GetByID(id uint, schemaName string) (*Staff, error)
	GetByUsername(username string, schemaName string) (*Staff, error)
	Create(staff *Staff, schemaName string) error
	Update(staff *Staff, schemaName string) error
	Delete(id uint, schemaName string) error
}

// StaffService interface - tenant isolation handled at schema level
type StaffService interface {
	Login(req *StaffLoginRequest, schemaName string) (*StaffLoginResponse, error)
	GetAll(schemaName string) ([]Staff, error)
	GetByID(id uint, schemaName string) (*Staff, error)
	Create(req *StaffCreateRequest, schemaName string) (*Staff, error)
	Update(id uint, req *StaffUpdateRequest, schemaName string) (*Staff, error)
	Delete(id uint, schemaName string) error
}
